# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '21'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: CmdLine@2
  displayName: Run Gradle tests
  inputs:
    script: |
      chmod +x ./gradlew
      ./gradlew clean test --no-daemon

- task: PublishTestResults@2
  displayName: Publish JUnit
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/build/test-results/test/TEST-*.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'Unit Tests'