trigger:
  branches:
    include:
      - main
      - build-pipeline
      - code-workflow

pr:
  branches:
    include:
      - main
      - code-workflow

pool:
  vmImage: 'windows-latest'

steps:
  # Use JDK 21
  - powershell: |
      Write-Host "Using JDK 21"
      Write-Host "##vso[task.setvariable variable=JAVA_HOME]$env:JAVA_HOME_21_X64"
      $env:JAVA_HOME = $env:JAVA_HOME_21_X64
      $env:Path = "$env:JAVA_HOME\bin;" + $env:Path
      java -version
    displayName: 'Select JDK 21 (preinstalled)'

  # Gradle Build
  - script: gradlew.bat clean build --no-daemon
    displayName: 'Gradle clean build'

  # Run Tests
  - script: gradlew.bat test --no-daemon
    displayName: 'Run unit tests'

  # ✅ Publish test results to Azure (JUnit XML)
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/build/test-results/test/TEST-*.xml'
      testRunTitle: 'Unit Test Results'
    displayName: 'Publish Test Results'

  # ✅ Publish Build Artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'build/libs'
      artifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish Build Artifacts'