# Azure Pipelines configuration for Java (Gradle) project
# Supports Windows agent, JDK 21, build & test, PR validation

trigger:
  branches:
    include:
      - feature/user-management/esha

pr:
  branches:
    include:
      - feature/user-management/esha

pool:
  vmImage: 'windows-latest'

steps:
  # JDK 21
  - powershell: |
      Write-Host "Using JDK 21"
      Write-Host "##vso[task.setvariable variable=JAVA_HOME]$env:JAVA_HOME_21_X64"
      $env:JAVA_HOME = $env:JAVA_HOME_21_X64
      $env:Path = "$env:JAVA_HOME\bin;" + $env:Path
      java -version
    displayName: 'Select JDK 21 (preinstalled)'

  # Gradle build
  - script: gradlew.bat clean build -x test --no-daemon
    displayName: 'Gradle clean build (without tests)'

  # Step 3: Gradle test and collect results
  - task: Gradle@2
    displayName: 'Run unit tests and publish results'
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew.bat'
      tasks: 'test'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      testRunTitle: 'Unit Tests - Betterpedia'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.21'



  # Step 4: upload build artifact
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'build/libs'
      artifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish build artifacts'
    condition: succeededOrFailed()


