trigger:
  branches:
    include:
      - main
      - build-pipeline

pr:
  branches:
    include:
      - main
      - build-pipeline

pool:
  vmImage: 'windows-latest'

steps:
  # JDK 21
  - powershell: |
      Write-Host "Use JDK 21"
      Write-Host "##vso[task.setvariable variable=JAVA_HOME]$env:JAVA_HOME_21_X64"
      $env:JAVA_HOME = $env:JAVA_HOME_21_X64
      $env:Path = "$env:JAVA_HOME\bin;" + $env:Path
      java -version
    displayName: 'Select JDK 21 (preinstalled)'

  # run Gradle build
  - script: gradlew.bat clean build --no-daemon
    displayName: 'Gradle clean build'

  # upload build artifact
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'build/libs'
      artifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish build artifacts'
