# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main
  - build-pipeline   # including the branch that I made (yein)

pool:
  vmImage: 'ubuntu-latest'

steps:
  # 1. install JDK (e.g. Java 17)
  - task: UseJavaVersion@1
    inputs:
      versionSpec: '17'
      distribution: 'zulu'
      cache: gradle

  # 2. build Gradle (gradlew )
  - script: ./gradlew build
    displayName: 'Build with Gradle'

  # 3. run test
  - script: ./gradlew test
    displayName: 'Run Unit Tests'

  # 4. upload artifact (store build result )
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'build/libs'
      artifactName: 'drop'
      publishLocation: 'Container'
