# Azure Pipelines configuration for Java (Gradle) project
# Supports JDK 21, build, test, and artifact publishing

trigger:
  branches:
    include:
      - main
      - feature/*

pr:
  branches:
    include:
      - main
      - feature/*

pool:
  vmImage: 'windows-latest'

steps:
  # Step 1: Set JDK 21
  - powershell: |
      Write-Host "Using JDK 21"
      Write-Host "##vso[task.setvariable variable=JAVA_HOME]$env:JAVA_HOME_21_X64"
      $env:JAVA_HOME = $env:JAVA_HOME_21_X64
      $env:Path = "$env:JAVA_HOME\bin;$env:Path"
      java -version
    displayName: 'Select JDK 21 (preinstalled)'

  # Step 2: Gradle build (without tests)
  - script: gradlew.bat clean build -x test --no-daemon
    displayName: 'Gradle clean build (skip tests)'

  # Step 3: Run unit tests and publish results
  - task: Gradle@3
    displayName: 'Run unit tests and publish results'
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew.bat'
      tasks: 'test'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      testRunTitle: 'Unit Tests - Betterpedia'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.21'

  # Step 4: Publish build artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/build/libs'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish build artifacts'
    condition: succeededOrFailed()