CREATE DATABASE IF NOT EXISTS wiki CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE wiki;

CREATE TABLE IF NOT EXISTS article (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(255) NOT NULL,
body LONGTEXT,
publish_date DATE,
lan VARCHAR(32)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS article_authors (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
article_id BIGINT NOT NULL,
author VARCHAR(255) NOT NULL,
CONSTRAINT fk_article_author
FOREIGN KEY (article_id) REFERENCES article(id) ON UPDATE CASCADE ON DELETE CASCADE,
UNIQUE KEY uk_article_author (article_id, author)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS article_tags (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
article_id BIGINT NOT NULL,
tag VARCHAR(64) NOT NULL,
CONSTRAINT fk_article_tag
FOREIGN KEY (article_id) REFERENCES article(id) ON UPDATE CASCADE ON DELETE CASCADE,
UNIQUE KEY uk_article_tag (article_id, tag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

