CREATE DATABASE IF NOT EXISTS wiki CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE wiki;
DROP TABLE IF EXISTS article;
CREATE TABLE IF NOT EXISTS article (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(255) NOT NULL,
body LONGTEXT,
publish_date DATE,
authors JSON NOT NULL,
tags JSON NOT NULL,
lan ENUM(
    'ENGLISH',
    'PERSIAN',
    'KOREAN',
    'FRENCH',
    'GERMAN',
    'CHINESE',
    'JAPANESE',
    'HINDI',
    'RUSSIAN'
    )
);


